/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kizmabirader;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author SAMET
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        jFrame1.setVisible(true);
        profileFrame.setVisible(true);
        profileFrame.pack();
        jFrame1.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profileFrame = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jFrame1 = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 160, 70));
        jLabel1.setText("Profile");

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 160, 70));
        jLabel3.setText("Choose Color");

        jToggleButton4.setBackground(new java.awt.Color(240, 248, 51));
        jToggleButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jToggleButton4.setText("Yellow");

        jToggleButton5.setBackground(new java.awt.Color(37, 81, 238));
        jToggleButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jToggleButton5.setText("Blue");

        jToggleButton6.setBackground(new java.awt.Color(66, 229, 30));
        jToggleButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jToggleButton6.setText("Green");

        jToggleButton7.setBackground(new java.awt.Color(255, 42, 25));
        jToggleButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jToggleButton7.setSelected(true);
        jToggleButton7.setText("Red");

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 160, 70));
        jLabel4.setText("Username");

        jTextField1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N

        jButton4.setBackground(new java.awt.Color(255, 160, 70));
        jButton4.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jButton4.setText("Main Menu");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout profileFrameLayout = new javax.swing.GroupLayout(profileFrame.getContentPane());
        profileFrame.getContentPane().setLayout(profileFrameLayout);
        profileFrameLayout.setHorizontalGroup(
            profileFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileFrameLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(profileFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(profileFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addGroup(profileFrameLayout.createSequentialGroup()
                            .addComponent(jToggleButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(profileFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(profileFrameLayout.createSequentialGroup()
                                    .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profileFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(182, 182, 182))
        );
        profileFrameLayout.setVerticalGroup(
            profileFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileFrameLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(profileFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jFrame1.setBackground(new java.awt.Color(255, 204, 0));
        jFrame1.setForeground(new java.awt.Color(153, 255, 102));
        jFrame1.setMinimumSize(new java.awt.Dimension(550, 530));
        jFrame1.setPreferredSize(new java.awt.Dimension(550, 530));
        jFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(37, 81, 238));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/blueColor.png"))); // NOI18N
        jLabel5.setText("a");
        jFrame1.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 11, 35, 35));

        jLabel6.setBackground(new java.awt.Color(37, 81, 238));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/blueColor.png"))); // NOI18N
        jLabel6.setText("a");
        jFrame1.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 35, 35));

        jLabel7.setBackground(new java.awt.Color(37, 81, 238));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/blueColor.png"))); // NOI18N
        jLabel7.setText("a");
        jFrame1.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 52, 35, 35));

        jLabel8.setBackground(new java.awt.Color(37, 81, 238));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/blueColor.png"))); // NOI18N
        jLabel8.setText("a");
        jFrame1.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, 35, 35));

        jLabel9.setBackground(new java.awt.Color(37, 81, 238));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/redColor.png"))); // NOI18N
        jLabel9.setText("a");
        jFrame1.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 35, 35));

        jLabel10.setBackground(new java.awt.Color(37, 81, 238));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/redColor.png"))); // NOI18N
        jLabel10.setText("a");
        jFrame1.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 35, 35));

        jLabel11.setBackground(new java.awt.Color(37, 81, 238));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/redColor.png"))); // NOI18N
        jLabel11.setText("a");
        jFrame1.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 35, 35));

        jLabel12.setBackground(new java.awt.Color(37, 81, 238));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/redColor.png"))); // NOI18N
        jLabel12.setText("a");
        jFrame1.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 35, 35));

        jLabel13.setBackground(new java.awt.Color(37, 81, 238));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/greenColor.png"))); // NOI18N
        jLabel13.setText("a");
        jFrame1.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, 35, 35));

        jLabel14.setBackground(new java.awt.Color(37, 81, 238));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/greenColor.png"))); // NOI18N
        jLabel14.setText("a");
        jFrame1.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, 35, 35));

        jLabel15.setBackground(new java.awt.Color(37, 81, 238));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/greenColor.png"))); // NOI18N
        jLabel15.setText("a");
        jFrame1.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 490, 35, 35));

        jLabel16.setBackground(new java.awt.Color(37, 81, 238));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/greenColor.png"))); // NOI18N
        jLabel16.setText("a");
        jFrame1.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, 35, 35));

        jLabel17.setBackground(new java.awt.Color(37, 81, 238));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/yellowColor.png"))); // NOI18N
        jLabel17.setText("a");
        jFrame1.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 35, 35));

        jLabel18.setBackground(new java.awt.Color(37, 81, 238));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/yellowColor.png"))); // NOI18N
        jLabel18.setText("a");
        jFrame1.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 35, 35));

        jLabel19.setBackground(new java.awt.Color(37, 81, 238));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/yellowColor.png"))); // NOI18N
        jLabel19.setText("a");
        jFrame1.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 35, 35));

        jLabel20.setBackground(new java.awt.Color(37, 81, 238));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/yellowColor.png"))); // NOI18N
        jLabel20.setText("a");
        jFrame1.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 35, 35));

        jLabel21.setBackground(new java.awt.Color(37, 81, 238));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel21.setText("a");
        jFrame1.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 35, 35));

        jLabel22.setBackground(new java.awt.Color(37, 81, 238));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel22.setText("a");
        jFrame1.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 35, 35));

        jLabel23.setBackground(new java.awt.Color(37, 81, 238));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel23.setText("a");
        jFrame1.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, 35, 35));

        jLabel24.setBackground(new java.awt.Color(37, 81, 238));
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel24.setText("a");
        jFrame1.getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, 35, 35));

        jLabel25.setBackground(new java.awt.Color(37, 81, 238));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel25.setText("a");
        jFrame1.getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, 35, 35));

        jLabel26.setBackground(new java.awt.Color(37, 81, 238));
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel26.setText("a");
        jFrame1.getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 35, 35));

        jLabel27.setBackground(new java.awt.Color(250, 128, 114));
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel27.setText("a");
        jFrame1.getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 35, 35));

        jLabel28.setBackground(new java.awt.Color(250, 128, 114));
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel28.setText("a");
        jFrame1.getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 35, 35));

        jLabel29.setBackground(new java.awt.Color(250, 128, 114));
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel29.setText("a");
        jFrame1.getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 35, 35));

        jLabel30.setBackground(new java.awt.Color(250, 128, 114));
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel30.setText("a");
        jFrame1.getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 35, 35));

        jLabel31.setBackground(new java.awt.Color(37, 81, 238));
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel31.setText("a");
        jFrame1.getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 35, 35));

        jLabel32.setBackground(new java.awt.Color(37, 81, 238));
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel32.setText("a");
        jFrame1.getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 35, 35));

        jLabel33.setBackground(new java.awt.Color(250, 128, 114));
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel33.setText("a");
        jFrame1.getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 35, 35));

        jLabel34.setBackground(new java.awt.Color(37, 81, 238));
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel34.setText("a");
        jFrame1.getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 35, 35));

        jLabel35.setBackground(new java.awt.Color(37, 81, 238));
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel35.setText("a");
        jFrame1.getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 35, 35));

        jLabel36.setBackground(new java.awt.Color(37, 81, 238));
        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel36.setText("a");
        jFrame1.getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 35, 35));

        jLabel37.setBackground(new java.awt.Color(37, 81, 238));
        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel37.setText("a");
        jFrame1.getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 35, 35));

        jLabel38.setBackground(new java.awt.Color(37, 81, 238));
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel38.setText("a");
        jFrame1.getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 35, 35));

        jLabel39.setBackground(new java.awt.Color(37, 81, 238));
        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel39.setText("a");
        jFrame1.getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 35, 35));

        jLabel40.setBackground(new java.awt.Color(37, 81, 238));
        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel40.setText("a");
        jFrame1.getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 35, 35));

        jLabel41.setBackground(new java.awt.Color(37, 81, 238));
        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel41.setText("a");
        jFrame1.getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 35, 35));

        jLabel42.setBackground(new java.awt.Color(250, 128, 114));
        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel42.setText("a");
        jFrame1.getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 35, 35));

        jLabel43.setBackground(new java.awt.Color(250, 128, 114));
        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel43.setText("a");
        jFrame1.getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 35, 35));

        jLabel44.setBackground(new java.awt.Color(250, 128, 114));
        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel44.setText("a");
        jFrame1.getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 35, 35));

        jLabel45.setBackground(new java.awt.Color(250, 128, 114));
        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel45.setText("a");
        jFrame1.getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 35, 35));

        jLabel46.setBackground(new java.awt.Color(250, 128, 114));
        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel46.setText("a");
        jFrame1.getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 35, 35));

        jLabel47.setBackground(new java.awt.Color(250, 128, 114));
        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel47.setText("a");
        jFrame1.getContentPane().add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 35, 35));

        jLabel48.setBackground(new java.awt.Color(250, 128, 114));
        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel48.setText("a");
        jFrame1.getContentPane().add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 35, 35));

        jLabel49.setBackground(new java.awt.Color(250, 128, 114));
        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel49.setText("a");
        jFrame1.getContentPane().add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 35, 35));

        jLabel50.setBackground(new java.awt.Color(37, 81, 238));
        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel50.setText("a");
        jFrame1.getContentPane().add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 35, 35));

        jLabel51.setBackground(new java.awt.Color(37, 81, 238));
        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel51.setText("a");
        jFrame1.getContentPane().add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 35, 35));

        jLabel52.setBackground(new java.awt.Color(37, 81, 238));
        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel52.setText("a");
        jFrame1.getContentPane().add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 35, 35));

        jLabel53.setBackground(new java.awt.Color(37, 81, 238));
        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel53.setText("a");
        jFrame1.getContentPane().add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 35, 35));

        jLabel54.setBackground(new java.awt.Color(37, 81, 238));
        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel54.setText("a");
        jFrame1.getContentPane().add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 35, 35));

        jLabel55.setBackground(new java.awt.Color(37, 81, 238));
        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel55.setText("a");
        jFrame1.getContentPane().add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 35, 35));

        jLabel56.setBackground(new java.awt.Color(37, 81, 238));
        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel56.setText("a");
        jFrame1.getContentPane().add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 35, 35));

        jLabel57.setBackground(new java.awt.Color(37, 81, 238));
        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel57.setText("a");
        jFrame1.getContentPane().add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 35, 35));

        jLabel58.setBackground(new java.awt.Color(37, 81, 238));
        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel58.setText("a");
        jFrame1.getContentPane().add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 35, 35));

        jLabel59.setBackground(new java.awt.Color(37, 81, 238));
        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel59.setText("a");
        jFrame1.getContentPane().add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 35, 35));

        jLabel60.setBackground(new java.awt.Color(37, 81, 238));
        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel60.setText("a");
        jFrame1.getContentPane().add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 35, 35));

        jLabel61.setBackground(new java.awt.Color(37, 81, 238));
        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel61.setText("a");
        jFrame1.getContentPane().add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 35, 35));

        jLabel62.setBackground(new java.awt.Color(37, 81, 238));
        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel62.setText("a");
        jFrame1.getContentPane().add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 35, 35));

        jLabel63.setBackground(new java.awt.Color(37, 81, 238));
        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel63.setText("a");
        jFrame1.getContentPane().add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 35, 35));

        jLabel64.setBackground(new java.awt.Color(37, 81, 238));
        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel64.setText("a");
        jFrame1.getContentPane().add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 35, 35));

        jLabel65.setBackground(new java.awt.Color(37, 81, 238));
        jLabel65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel65.setText("a");
        jFrame1.getContentPane().add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 35, 35));

        jLabel66.setBackground(new java.awt.Color(37, 81, 238));
        jLabel66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel66.setText("a");
        jFrame1.getContentPane().add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 35, 35));

        jLabel67.setBackground(new java.awt.Color(37, 81, 238));
        jLabel67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel67.setText("a");
        jFrame1.getContentPane().add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 35, 35));

        jLabel68.setBackground(new java.awt.Color(37, 81, 238));
        jLabel68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel68.setText("a");
        jFrame1.getContentPane().add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 35, 35));

        jLabel69.setBackground(new java.awt.Color(250, 128, 114));
        jLabel69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel69.setText("a");
        jFrame1.getContentPane().add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 35, 35));

        jLabel70.setBackground(new java.awt.Color(250, 128, 114));
        jLabel70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel70.setText("a");
        jFrame1.getContentPane().add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 35, 35));

        jLabel71.setBackground(new java.awt.Color(250, 128, 114));
        jLabel71.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel71.setText("a");
        jFrame1.getContentPane().add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 35, 35));

        jLabel72.setBackground(new java.awt.Color(250, 128, 114));
        jLabel72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel72.setText("a");
        jFrame1.getContentPane().add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 35, 35));

        jLabel73.setBackground(new java.awt.Color(250, 128, 114));
        jLabel73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel73.setText("a");
        jFrame1.getContentPane().add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 35, 35));

        jLabel74.setBackground(new java.awt.Color(250, 128, 114));
        jLabel74.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel74.setText("a");
        jFrame1.getContentPane().add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 35, 35));

        jLabel75.setBackground(new java.awt.Color(250, 128, 114));
        jLabel75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel75.setText("a");
        jFrame1.getContentPane().add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 35, 35));

        jLabel76.setBackground(new java.awt.Color(250, 128, 114));
        jLabel76.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel76.setText("a");
        jFrame1.getContentPane().add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 35, 35));

        jLabel77.setBackground(new java.awt.Color(37, 81, 238));
        jLabel77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel77.setText("a");
        jFrame1.getContentPane().add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 35, 35));

        jLabel78.setBackground(new java.awt.Color(37, 81, 238));
        jLabel78.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel78.setText("a");
        jFrame1.getContentPane().add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 35, 35));

        jLabel79.setBackground(new java.awt.Color(37, 81, 238));
        jLabel79.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel79.setText("a");
        jFrame1.getContentPane().add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 35, 35));

        jLabel80.setBackground(new java.awt.Color(37, 81, 238));
        jLabel80.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel80.setText("a");
        jFrame1.getContentPane().add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 35, 35));

        jLabel81.setBackground(new java.awt.Color(37, 81, 238));
        jLabel81.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel81.setText("a");
        jFrame1.getContentPane().add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 35, 35));

        jLabel82.setBackground(new java.awt.Color(37, 81, 238));
        jLabel82.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel82.setText("a");
        jFrame1.getContentPane().add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 35, 35));

        jLabel83.setBackground(new java.awt.Color(37, 81, 238));
        jLabel83.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel83.setText("a");
        jFrame1.getContentPane().add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 35, 35));

        jLabel84.setBackground(new java.awt.Color(37, 81, 238));
        jLabel84.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel84.setText("a");
        jFrame1.getContentPane().add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 35, 35));

        jLabel85.setBackground(new java.awt.Color(250, 128, 114));
        jLabel85.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel85.setText("a");
        jFrame1.getContentPane().add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 35, 35));

        jLabel86.setBackground(new java.awt.Color(250, 128, 114));
        jLabel86.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel86.setText("a");
        jFrame1.getContentPane().add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 35, 35));

        jLabel87.setBackground(new java.awt.Color(250, 128, 114));
        jLabel87.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel87.setText("a");
        jFrame1.getContentPane().add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 35, 35));

        jLabel88.setBackground(new java.awt.Color(250, 128, 114));
        jLabel88.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel88.setText("a");
        jFrame1.getContentPane().add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 35, 35));

        jLabel89.setBackground(new java.awt.Color(250, 128, 114));
        jLabel89.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel89.setText("a");
        jFrame1.getContentPane().add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 35, 35));

        jLabel90.setBackground(new java.awt.Color(250, 128, 114));
        jLabel90.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel90.setText("a");
        jFrame1.getContentPane().add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 35, 35));

        jLabel91.setBackground(new java.awt.Color(250, 128, 114));
        jLabel91.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel91.setText("a");
        jFrame1.getContentPane().add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 35, 35));

        jLabel92.setBackground(new java.awt.Color(250, 128, 114));
        jLabel92.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel92.setText("a");
        jFrame1.getContentPane().add(jLabel92, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 35, 35));

        jLabel93.setBackground(new java.awt.Color(250, 128, 114));
        jLabel93.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel93.setText("a");
        jFrame1.getContentPane().add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 35, 35));

        jLabel94.setBackground(new java.awt.Color(250, 128, 114));
        jLabel94.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel94.setText("a");
        jFrame1.getContentPane().add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 35, 35));

        jLabel95.setBackground(new java.awt.Color(37, 81, 238));
        jLabel95.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel95.setText("a");
        jFrame1.getContentPane().add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 35, 35));

        jLabel96.setBackground(new java.awt.Color(37, 81, 238));
        jLabel96.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel96.setText("a");
        jFrame1.getContentPane().add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 35, 35));

        jLabel97.setBackground(new java.awt.Color(37, 81, 238));
        jLabel97.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel97.setText("a");
        jFrame1.getContentPane().add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 35, 35));

        jLabel98.setBackground(new java.awt.Color(37, 81, 238));
        jLabel98.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kizmabirader/images/salmonColor.png"))); // NOI18N
        jLabel98.setText("a");
        jFrame1.getContentPane().add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 35, 35));

        jButton5.setText("Dice");
        jFrame1.getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 70, 40));

        jTextField2.setBackground(new java.awt.Color(140, 225, 245));
        jTextField2.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 48)); // NOI18N
        jTextField2.setText("0");
        jFrame1.getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, 40));

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        jFrame1.getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, -1, 400, 660));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(230, 144, 41));
        jLabel2.setText("Kızma Birader");

        jButton1.setBackground(new java.awt.Color(255, 160, 70));
        jButton1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jButton1.setText("New Game");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 160, 70));
        jButton2.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jButton2.setText("Profile");

        jButton3.setBackground(new java.awt.Color(255, 160, 70));
        jButton3.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jButton3.setText("Settings");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel2)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JFrame profileFrame;
    // End of variables declaration//GEN-END:variables
}
